name: CI

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
    - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter format --set-exit-if-changed .
      - run: flutter analyze .
      - run: flutter test
      - run: flutter build apk
        uses: actions/upload-artifact@master
        with:
          name: apk-release
          path: build/app/outputs/bundle/release/app-release.apk
